alex/urls.py
from django.urls import path


from alex import views

urlpatterns = [
    path('contact/', views.ContactCreateView.as_view(), name='create_contact'),
    path('galery/', views. GaleryTemplateView.as_view(), name='galery'),
    path('list_products/', views.ProductListView.as_view(), name='list-products'),
    path('cart/', views.cart_view, name='cart'),
    path('add_to_card/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout_view, name='checkout_view'),
    path('create_rev/', views.RevCreateView.as_view(), name='create-rev'),
    path('list_rev/', views.RevListView.as_view(), name='list-rev'),
    path('delete_rev/<int:pk>/', views.RevDeleteView.as_view(), name='delete-rev'),
    path('details_rev/<int:pk>/', views.RevDetailView.as_view(), name='details-rev'),

]

turism/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('userextend.urls')),
    path('', include('alex.urls')),

    path("accounts/login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alex/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


class SiteUser(AbstractUser):
    def __str__(self):
        return self.last_name + " " + self.first_name

class Article(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    author = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.name



class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=255)
    message = models.TextField()



class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=2)
    photo = models.ImageField(upload_to='static/', null=True, blank=True)

    def __str__(self):
        return self.name

class Cart(models.Model):
    STATUS = [
        ('open', 'Open'),
        ('closed', 'Closed'),
    ]
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS, default='open')





class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)


class Rev(models.Model):

    nota_options = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )


    prenumele = models.CharField(max_length=40)
    nume = models.CharField(max_length=40)
    email = models.EmailField(max_length=60)
    descriere = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    excursia = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    nota = models.CharField(max_length=6, choices=nota_options, default="1")


    def __str__(self):
        return f'{self.prenumele} {self.nume}'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Cos de Cumparaturi</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600&family=Roboto&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>


<!-- Navbar start -->
<div class="container-fluid fixed-top px-0">
    <div class="container px-0">
        <div class="topbar">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-8">
                    <div class="topbar-info d-flex flex-wrap">
                        <a href="#" class="text-light me-4"><i class="fas fa-envelope text-white me-2"></i>CalătoreșteCuNoi@gmail.com</a>
                        <a href="#" class="text-light"><i class="fas fa-phone-alt text-white me-2"></i>+0712345678</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="topbar-icon d-flex align-items-center justify-content-end">
                        <a href="#" class="btn-square text-white me-2"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" class="btn-square text-white me-2"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="btn-square text-white me-2"><i class="fab fa-instagram"></i></a>
                        <a href="#" class="btn-square text-white me-2"><i class="fab fa-pinterest"></i></a>
                        <a href="#" class="btn-square text-white me-0"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-light bg-light navbar-expand-xl">
            <a href="{% url 'homepage' %}" class="navbar-brand ms-3">
                <h1 class="text-primary display-5">CalătoreșteCuNoi</h1>
            </a>
            <button class="navbar-toggler py-2 px-3 me-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse">
                <span class="fa fa-bars text-primary"></span>
            </button>
            <div class="collapse navbar-collapse bg-light" id="navbarCollapse">
                <div class="navbar-nav ms-auto">
                    <a href="{% url 'homepage' %}" class="nav-item nav-link active">Acasa</a>
                    <a href="{% url 'list-products' %}" class="nav-item nav-link">Servicii</a>
                    <a href="{% url 'galery' %}" class="nav-item nav-link">Galerie</a>
                </div>
                
                {% if user.is_authenticated %}
                 <div class="navbar-nav ms-auto">
                    <a href="{% url 'create-rev' %}" class="nav-item nav-link">Creaza o recenzie</a>
                    <a href="{% url 'list-rev' %}" class="nav-item nav-link">Lista recenzii</a>
                </div>
                {% endif %}
                <a href="{% url 'create_contact' %}" class="nav-item nav-link active">Contact</a>
            </div>
        
                       
                      

        
            <a class="navbar-brand" href="{% url 'cart' %}"><img src="{% static 'img/cart_icon.png' %}" height="36"
                                                                 width="36"
                                                                 alt="..."/></a>
            <a class="navbar-brand"
               href="https://act.greenpeace.ro/doneaza/?utm_source=greenpeace.org&utm_medium=referral&utm_campaign=donate+button&_ga=2.136734005.446026110.1715546654-1686669088.1715546654"
               target="_blank"><img src="{% static 'img/tree icon.png' %}"
                                    alt="..." height="36" width="36"/></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars ms-1"></i>
            </button>
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary">Logout, {{ user.username }}</button>
                </form>
            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
                    <a href="{% url 'create-user' %}" class="btn btn-outline-secondary">Sign up</a>
                </div>
            {% endif %}

        </nav>
    </div>
</div>
<!-- Navbar End -->


<img src="{% static 'img/white.png' %}">

<div class="container">
    <div class="row mt-10">
        {#        <div class="col-md-6">#}
        {% for cart_item in cart.cartitem_set.all %}
            <div class="col-md-7">
                <div class="row mt-6">
                    <div class="card border border-dark">
                        {#                        <img src="{{ cart_item.product.photo.url }}" class="card-img-top" alt="imagine_profil"#}
                        {#                             height="450"#}
                        {#                             style="object-fit: cover">#}
                        <div class="card-body">
                            <h5 class="card-title">{{ cart_item.product.name }}</h5>
                            <p class="card-text">Pret: {{ cart_item.product.price }}</p>
                            <p class="card-text">Quantity: {{ cart_item.quantity }}</p>
                            <form action="{% url 'add_to_cart' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ cart_item.product.id }}">
                                <input type="hidden" name="quantity" value="-{{ cart_item.quantity }}">
                                <button type="submit" class="btn btn-primary">Remove Item</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        {% empty %}

            <div class="col-md-4">
                <img src="{% static 'img/empty_cart.png' %}" alt="..." height="800" width="800"/>
            </div>
        {% endfor %}

        {#         {% for cart_item in cart.cartitem_set.all %}#}
        {#             total = o#}
        {#             total += cart_item.price#}
        {#        {% endfor %}#}


        {#        </div>#}
    </div>
</div>
<div class="container" style="padding-top: 50px;
  padding-bottom: 20px;
  padding-left: 30px;
  padding-right: 40px;">


    <form action="{% url 'checkout_view' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">Cumpara!</button>
    </form>
</div>

</body>
</html>